export const INITIAL_ARTWORKS = [

  {
    id: 'art-1',
    title: 'Golden Lion King Warrior',
    artist: {
      name: 'Kaelen Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
      handle: 'kaelenv',
      followedByMe: false,
      role: 'Senior Matte Painter'
    },
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'An extremely detailed study on heavy golden armor plates, sculpted with divine feline details. Modelled in ZBrush and rendered in Cinema4D with Octane Renderer.',
    likes: 3120,
    likedByMe: false,
    views: 12430,
    tags: ['character', 'lion', 'armor', 'zbrush', 'fantasy'],
    software: ['ZBrush', 'Cinema 4D', 'Octane'],
    createdAt: '2026-05-28',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-2',
    title: 'Abyssal Horror Cthulhu',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'A terrifying creature of the deep. Sculpted organic wrinkles, wet shaders, and intricate tentacles reaching from the shadows.',
    likes: 2450,
    likedByMe: false,
    views: 8900,
    tags: ['creature', '3d', 'sculpt', 'cthulhu', 'organic'],
    software: ['ZBrush', 'Substance Painter'],
    createdAt: '2026-05-27',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-3',
    title: 'Biotanipunk Core Concept',
    artist: {
      name: 'Marcus Vance',
      avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=150&auto=format&fit=crop',
      handle: 'marcus_v',
      followedByMe: false,
      role: 'Digital Architect'
    },
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b??w=400&q=60&auto=format&fit=crop', 
    category: 'Environment',
    description: 'Minimalist sci-fi environment structure overgrown with bright green moss and glowing orange biotextures.',
    likes: 1890,
    likedByMe: false,
    views: 11200,
    tags: ['futuristic', 'landscape', 'biotanipunk', 'concept'],
    software: ['Photoshop', 'Blender'],
    createdAt: '2026-05-26',
    comments: [],
    brandOverlay: 'BIOTANIPUNK'
  },
  {
    id: 'art-4',
    title: 'Diablo IV: Lord of Hatred Coast',
    artist: {
      name: 'Kenji Takahashi',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
      handle: 'kenjidigital',
      followedByMe: false,
      role: 'Environment Illustrator'
    },
    image: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'A dark, moody coastal landscape with crumbling gothic towers and blood-red waves inspired by Diablo lore.',
    likes: 4210,
    likedByMe: false,
    views: 23100,
    tags: ['diablo', 'darkfantasy', 'illustration', 'coast', 'gothic'],
    software: ['Photoshop', 'Procreate'],
    createdAt: '2026-05-25',
    comments: [],
    brandOverlay: 'DIABLO'
  },

  {
    id: 'art-5',
    title: 'Rear-View Tactical Exosuit',
    artist: {
      name: 'Aron Cole',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
      handle: 'aronc_art',
      followedByMe: false,
      role: 'Heavy Surface Modeler'
    },
    image: 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Hard surface modelling of sleek carbon-fiber armor panels and mechanical joint interfaces on a tactical runner archetype.',
    likes: 3820,
    likedByMe: false,
    views: 16900,
    tags: ['characters', 'mech', 'hardsurface', 'sci-fi'],
    software: ['Maya', 'Substance Painter'],
    createdAt: '2026-05-24',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-6',
    title: 'Slavic Core Village Craft',
    artist: {
      name: 'Kaelen Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
      handle: 'kaelenv',
      followedByMe: false,
      role: 'Senior Matte Painter'
    },
    image: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'Whimsical, colorful village architecture with steep red roofs and snowy accents in Slavic core aesthetic.',
    likes: 1950,
    likedByMe: false,
    views: 9400,
    tags: ['slavic', 'illustration', 'town', 'fantasy'],
    software: ['Photoshop', 'Corel Painter'],
    createdAt: '2026-05-23',
    comments: [],
    brandOverlay: 'SLAVIC CORE'
  },
  {
    id: 'art-7',
    title: 'Smiling Woman Portrait Study',
    artist: {
      name: 'Sera Arttech',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
      handle: 'sera_art',
      followedByMe: false,
      role: 'Digital Painter'
    },
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'A loose, expressive portrait study focusing on realistic facial structures, lighting, and messy black hair movement.',
    likes: 2710,
    likedByMe: false,
    views: 11300,
    tags: ['portrait', 'painting', 'sketch', 'digitalpainting'],
    software: ['Photoshop'],
    createdAt: '2026-05-22',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-8',
    title: 'Overwatch Style Character',
    artist: {
      name: 'Kenji Takahashi',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
      handle: 'kenjidigital',
      followedByMe: false,
      role: 'Environment Illustrator'
    },
    image: 'https://images.unsplash.com/photo-1560942485-b2a11cc13456??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Stylized 3D character design of an eared pilot wearing futuristic orange and white gear.',
    likes: 4950,
    likedByMe: false,
    views: 29000,
    tags: ['overwatch', 'fanart', '3d', 'characterdesign'],
    software: ['ZBrush', 'Substance Painter', 'Blender'],
    createdAt: '2026-05-21',
    comments: [],
    brandOverlay: 'OVERWATCH'
  },

  {
    id: 'art-9',
    title: 'Golden Ring Mech Overlord',
    artist: {
      name: 'Aron Cole',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
      handle: 'aronc_art',
      followedByMe: false,
      role: 'Heavy Surface Modeler'
    },
    image: 'https://images.unsplash.com/photo-1500964757637-c85e8a162699??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'An imposing sci-fi robotic machine with glowing gold and white circular gravity rings floating around its torso.',
    likes: 1820,
    likedByMe: false,
    views: 8100,
    tags: ['robot', '3d', 'hardsurface', 'scifi'],
    software: ['Unreal Engine 5', 'Blender'],
    createdAt: '2026-05-20',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-10',
    title: 'Cyber Void purple Ninja',
    artist: {
      name: 'Marcus Vance',
      avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=150&auto=format&fit=crop',
      handle: 'marcus_v',
      followedByMe: false,
      role: 'Digital Architect'
    },
    image: 'https://images.unsplash.com/photo-1535663110196-5d042c140446??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Concept design of a futuristic ninja with sharp purple shards and a fully illuminated bio-helmet.',
    likes: 2150,
    likedByMe: false,
    views: 12100,
    tags: ['characters', 'ninja', 'concept', 'cyberpunk'],
    software: ['Procreate', 'Photoshop'],
    createdAt: '2026-05-19',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-11',
    title: 'Gladiator Champion Unreal Scene',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1559893088-c0787ebfc084??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'An heavily bandaged rope warrior made in Unreal Engine, demonstrating advanced texture realism and light shading.',
    likes: 3110,
    likedByMe: false,
    views: 14200,
    tags: ['unreal', '3d', 'render', 'gladiator'],
    software: ['Unreal Engine 5', 'ZBrush'],
    createdAt: '2026-05-18',
    comments: [],
    brandOverlay: 'UNREAL'
  },
  {
    id: 'art-12',
    title: 'Ancient Elder Forest Golem',
    artist: {
      name: 'Kaelen Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
      handle: 'kaelenv',
      followedByMe: false,
      role: 'Senior Matte Painter'
    },
    image: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9??w=400&q=60&auto=format&fit=crop', 
    category: '2D',
    description: 'A gentle colossal protector made of living roots, oak branches, and stone armor plates.',
    likes: 1720,
    likedByMe: false,
    views: 6500,
    tags: ['golem', 'forest', 'fantasy', 'illustration'],
    software: ['Photoshop'],
    createdAt: '2026-05-17',
    comments: [],
    brandOverlay: undefined
  },

  {
    id: 'art-13',
    title: 'Mechanical Engine Grill study',
    artist: {
      name: 'Aron Cole',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
      handle: 'aronc_art',
      followedByMe: false,
      role: 'Heavy Surface Modeler'
    },
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'A study on extremely high-density polygon mechanical structures, heat pipes, and exhaust valves.',
    likes: 950,
    likedByMe: false,
    views: 4100,
    tags: ['engine', 'machinery', 'hardsurface'],
    software: ['Marmoset Toolbag', 'Maya'],
    createdAt: '2026-05-16',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-14',
    title: 'Crescent Moon Shaman Cultist',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'A female skull shaman bound in leather bandages, holding high-contrast visual feather emblems and crescent moon decorations.',
    likes: 1980,
    likedByMe: false,
    views: 9200,
    tags: ['shaman', 'characters', 'cultist', 'fantasy'],
    software: ['ZBrush', 'Photoshop'],
    createdAt: '2026-05-15',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-15',
    title: 'Middle-Eastern Islamic Dome Ruins',
    artist: {
      name: 'Marcus Vance',
      avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=150&auto=format&fit=crop',
      handle: 'marcus_v',
      followedByMe: false,
      role: 'Digital Architect'
    },
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523??w=400&q=60&auto=format&fit=crop', 
    category: 'Environment',
    description: 'Gorgeous white dome structures built into sunlit canyon edges, rendered in beautiful daylight with crowd overlays.',
    likes: 2110,
    likedByMe: false,
    views: 10400,
    tags: ['mosque', 'dome', 'sandcastle', 'ruins'],
    software: ['Unreal Engine 5', 'Houdini'],
    createdAt: '2026-05-14',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-16',
    title: 'Indiana Jones: Rug Pattern Material',
    artist: {
      name: 'Sera Arttech',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
      handle: 'sera_art',
      followedByMe: false,
      role: 'Digital Painter'
    },
    image: 'https://images.unsplash.com/photo-1582139329536-e7284fece509??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'Highly detailed rug pattern designs handcrafted for Indiana Jones and the Great Circle cinematic assets.',
    likes: 3420,
    likedByMe: false,
    views: 15600,
    tags: ['indiana-jones', 'material', 'rug', 'pattern'],
    software: ['Substance Designer', 'Photoshop'],
    createdAt: '2026-05-13',
    comments: [],
    brandOverlay: 'INDIANA JONES'
  },

  {
    id: 'art-17',
    title: 'Cyber Wolf & Soldiers in Mist',
    artist: {
      name: 'Kenji Takahashi',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
      handle: 'kenjidigital',
      followedByMe: false,
      role: 'Environment Illustrator'
    },
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5??w=400&q=60&auto=format&fit=crop', 
    category: 'Environment',
    description: 'A sci-fi operative walking alongside a robotic beast with glowing red eyes in a desolate cold city street.',
    likes: 2900,
    likedByMe: false,
    views: 14000,
    tags: ['cyber', 'soldier', 'beast', 'rain'],
    software: ['Photoshop'],
    createdAt: '2026-05-12',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-18',
    title: 'Sunyata Myths: Sorrowful Lovers',
    artist: {
      name: 'Sera Arttech',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
      handle: 'sera_art',
      followedByMe: false,
      role: 'Digital Painter'
    },
    image: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'Close-up of a sorrowful dark-haired woman holding her lover. Branded with the mythological Sunyata myths layout.',
    likes: 2430,
    likedByMe: false,
    views: 9900,
    tags: ['sunyata', 'myths', 'illustration', 'sorrow'],
    software: ['Procreate'],
    createdAt: '2026-05-11',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-19',
    title: 'Transformers Optimus Prime Render',
    artist: {
      name: 'Aron Cole',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
      handle: 'aronc_art',
      followedByMe: false,
      role: 'Heavy Surface Modeler'
    },
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'A comprehensive multi-angle hard-surface render breakdown of Optimus and Bumblebee robot forms.',
    likes: 1840,
    likedByMe: false,
    views: 7900,
    tags: ['transformers', 'mecha', 'action', '3d'],
    software: ['Maya', 'Substance Painter'],
    createdAt: '2026-05-10',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-20',
    title: 'Elden Ring II: Abyssal Serpent',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'Fan art exploration of a rumored boss from Elden Ring sequel - the terrifying multi-tentacled Abyssal Serpent.',
    likes: 5600,
    likedByMe: false,
    views: 31000,
    tags: ['elden-ring', 'monster', 'serpent', 'abyssal'],
    software: ['Photoshop', 'Corel Painter'],
    createdAt: '2026-05-09',
    comments: [],
    brandOverlay: 'ELDEN RING'
  },

  {
    id: 'art-21',
    title: 'Hi-Mesh Modern Tactical Knife',
    artist: {
      name: 'Aron Cole',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
      handle: 'aronc_art',
      followedByMe: false,
      role: 'Heavy Surface Modeler'
    },
    image: 'https://images.unsplash.com/photo-1594489428504-5c0c480a15fd??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'A study on extremely clean hard-surface topologies for a foldable survival pocket knife tool.',
    likes: 1300,
    likedByMe: false,
    views: 5200,
    tags: ['knife', 'weapon', 'hardsurface', 'industrial'],
    software: ['Rhino', 'Marmoset'],
    createdAt: '2026-05-08',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-22',
    title: 'League of Legends: Amumu Noodle',
    artist: {
      name: 'Kaelen Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
      handle: 'kaelenv',
      followedByMe: false,
      role: 'Senior Matte Painter'
    },
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'Stylized noodle-golem character art tribute of Amumu from League of Legends.',
    likes: 3120,
    likedByMe: false,
    views: 14200,
    tags: ['league-of-legends', 'amumu', 'noodle', 'illustration'],
    software: ['Photoshop'],
    createdAt: '2026-05-07',
    comments: [],
    brandOverlay: 'LEAGUE OF LEGENDS'
  },
  {
    id: 'art-23',
    title: '3D Barrel Hammer Hammer',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'Handcrafted stylized medieval battle mallet fashioned with steel bands and a stout wooden barrel head.',
    likes: 1100,
    likedByMe: false,
    views: 4300,
    tags: ['prop', '3d', 'stylized', 'weapon'],
    software: ['ZBrush', 'Substance Painter'],
    createdAt: '2026-05-06',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-24',
    title: 'Rogue Elf shadows illustration',
    artist: {
      name: 'Kenji Takahashi',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
      handle: 'kenjidigital',
      followedByMe: false,
      role: 'Environment Illustrator'
    },
    image: 'https://images.unsplash.com/photo-1519074069444-1ba4e6664104??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'Stunning painterly piece showing a green-clothed scout looking towards crystals glowing in deep caverns.',
    likes: 2700,
    likedByMe: false,
    views: 11500,
    tags: ['rogue', 'elf', 'fantasy', 'gemstone'],
    software: ['Photoshop', 'Procreate'],
    createdAt: '2026-05-05',
    comments: [],
    brandOverlay: undefined
  },

  {
    id: 'art-25',
    title: 'Broken Gear Road construct',
    artist: {
      name: 'Marcus Vance',
      avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=150&auto=format&fit=crop',
      handle: 'marcus_v',
      followedByMe: false,
      role: 'Digital Architect'
    },
    image: 'https://images.unsplash.com/photo-1584483768514-df6990969b83??w=400&q=60&auto=format&fit=crop', 
    category: 'Environment',
    description: 'Hyper-realistic study of a damaged diagonal street construction barricade, labeled Broken Gear.',
    likes: 920,
    likedByMe: false,
    views: 3800,
    tags: ['sign', 'barricade', 'scenic', 'texturing'],
    software: ['Substance Painter', 'Unreal Engine 5'],
    createdAt: '2026-05-04',
    comments: [],
    brandOverlay: 'BROKEN GEAR'
  },
  {
    id: 'art-26',
    title: 'Plush Royal Golem Mascot',
    artist: {
      name: 'Sera Arttech',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
      handle: 'sera_art',
      followedByMe: false,
      role: 'Digital Painter'
    },
    image: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Soft-body cartoon toy study of a cute pink crowned furry creature. Handpainted texture maps.',
    likes: 1650,
    likedByMe: false,
    views: 6900,
    tags: ['character', 'mascot', 'fluffy', 'cartoon'],
    software: ['ZBrush', 'Cinema 4D'],
    createdAt: '2026-05-03',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-27',
    title: 'Gothic Arch Relighting set',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'Relighting showcase of decay cathedral stone pillars under frozen winter winds in Unreal Engine 5.',
    likes: 3820,
    likedByMe: false,
    views: 14700,
    tags: ['unreal', 'lighting', 'arches', 'winter'],
    software: ['Unreal Engine 5'],
    createdAt: '2026-05-02',
    comments: [],
    brandOverlay: 'RELIGHTING'
  },
  {
    id: 'art-28',
    title: 'Hairstyle Silhouette painting',
    artist: {
      name: 'Sera Arttech',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
      handle: 'sera_art',
      followedByMe: false,
      role: 'Digital Painter'
    },
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Anatomical model hair styling research. Perfect volumetric strokes on deep grey canvas.',
    likes: 1210,
    likedByMe: false,
    views: 5200,
    tags: ['hair', 'silhouette', 'study'],
    software: ['Photoshop'],
    createdAt: '2026-05-01',
    comments: [],
    brandOverlay: undefined
  },

  {
    id: 'art-29',
    title: 'Assault Weapon Scope Close-Up',
    artist: {
      name: 'Aron Cole',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
      handle: 'aronc_art',
      followedByMe: false,
      role: 'Heavy Surface Modeler'
    },
    image: 'https://images.unsplash.com/photo-1595590424283-b8f17842773f??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'Hard-surface breakdown of a tactical sniper scope sight element with wear patterns.',
    likes: 1450,
    likedByMe: false,
    views: 6100,
    tags: ['scope', 'gun', 'hardsurface'],
    software: ['Maya', 'Substance Painter'],
    createdAt: '2026-04-30',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-30',
    title: 'Alien Biomech Toxic Warrior',
    artist: {
      name: 'Kenji Takahashi',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
      handle: 'kenjidigital',
      followedByMe: false,
      role: 'Environment Illustrator'
    },
    image: 'https://images.unsplash.com/photo-1563089145-599997674d42??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'concept model of a biomechanical soldier covered in glowing viscous green sludge.',
    likes: 2120,
    likedByMe: false,
    views: 8900,
    tags: ['alien', 'soldier', 'toxic', 'concept'],
    software: ['ZBrush', 'Photoshop'],
    createdAt: '2026-04-29',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-31',
    title: 'Organic tumor beast horror',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1500485035595-cbe6f645feb1??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'Macabre design of custom tumor cells and alien organic growth structures.',
    likes: 1390,
    likedByMe: false,
    views: 5900,
    tags: ['organism', 'horror', 'creature'],
    software: ['ZBrush', 'Marmoset'],
    createdAt: '2026-04-28',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-32',
    title: 'Zugzug Fortress Gate',
    artist: {
      name: 'Marcus Vance',
      avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=150&auto=format&fit=crop',
      handle: 'marcus_v',
      followedByMe: false,
      role: 'Digital Architect'
    },
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23??w=400&q=60&auto=format&fit=crop', 
    category: 'Environment',
    description: 'Fantasy mentorship landscape artwork showing stone portals and neon crystals at deep vault levels.',
    likes: 2980,
    likedByMe: false,
    views: 11200,
    tags: ['zugzug', 'mentorship', 'fortress', 'fantasy'],
    software: ['Photoshop', 'Blender'],
    createdAt: '2026-04-27',
    comments: [],
    brandOverlay: undefined
  },

  {
    id: 'art-33',
    title: 'Sunken wooden ship valley ribs',
    artist: {
      name: 'Kaelen Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
      handle: 'kaelenv',
      followedByMe: false,
      role: 'Senior Matte Painter'
    },
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b??w=400&q=60&auto=format&fit=crop', 
    category: 'Environment',
    description: 'Ancient decaying ribs of a giant wooden ship buried deep inside mossy valley hills.',
    likes: 1910,
    likedByMe: false,
    views: 7400,
    tags: ['shipwreck', 'valleys', 'landscape'],
    software: ['Photoshop'],
    createdAt: '2026-04-26',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-34',
    title: 'Q-Police Tactical Helmet',
    artist: {
      name: 'Aron Cole',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
      handle: 'aronc_art',
      followedByMe: false,
      role: 'Heavy Surface Modeler'
    },
    image: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'White and grey hard-surface helmet design with diagnostic feedback hud.',
    likes: 1420,
    likedByMe: false,
    views: 5900,
    tags: ['helmet', 'hardsurface', 'sci-fi'],
    software: ['Maya', 'Keyshot'],
    createdAt: '2026-04-25',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-35',
    title: 'Ice Crown Frostmourne Weapon',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'Frozen broadsword decoration designed with complex frost skulls and glowing blue ice gems.',
    likes: 3120,
    likedByMe: false,
    views: 12000,
    tags: ['sword', 'ice', 'prop', 'blizzard'],
    software: ['Blender', 'ZBrush'],
    createdAt: '2026-04-24',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-36',
    title: 'Survival Truck highway sunset',
    artist: {
      name: 'Marcus Vance',
      avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=150&auto=format&fit=crop',
      handle: 'marcus_v',
      followedByMe: false,
      role: 'Digital Architect'
    },
    image: 'https://images.unsplash.com/photo-1511497584788-876760111969??w=400&q=60&auto=format&fit=crop', 
    category: 'Environment',
    description: 'Desolate yellow truck parked on a crumbling highway border at a warm pink sunset.',
    likes: 1850,
    likedByMe: false,
    views: 7400,
    tags: ['truck', 'highway', 'sunset', 'survival'],
    software: ['Photoshop'],
    createdAt: '2026-04-23',
    comments: [],
    brandOverlay: undefined
  },

  {
    id: 'art-37',
    title: 'Unreal Engine Dreadlocks Guy model',
    artist: {
      name: 'Sera Arttech',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
      handle: 'sera_art',
      followedByMe: false,
      role: 'Digital Painter'
    },
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Fidelity volumetric dreadlocks rendering research in Unreal Engine 5 with metahuman shaders.',
    likes: 2150,
    likedByMe: false,
    views: 9400,
    tags: ['unreal', 'metahuman', 'dreadlocks', 'man'],
    software: ['Unreal Engine 5'],
    createdAt: '2026-04-22',
    comments: [],
    brandOverlay: 'UNREAL'
  },
  {
    id: 'art-38',
    title: 'Bearded Knight metal plate Lord',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1500048993953-d23a436266cf??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Noble old knight with white beard and decorated red metallic shoulder guard plate.',
    likes: 3890,
    likedByMe: false,
    views: 16900,
    tags: ['knight', 'elder', 'armor', 'fantasycharacter'],
    software: ['ZBrush', 'Substance Painter'],
    createdAt: '2026-04-21',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-39',
    title: 'Telescope gun military scope sight',
    artist: {
      name: 'Aron Cole',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
      handle: 'aronc_art',
      followedByMe: false,
      role: 'Heavy Surface Modeler'
    },
    image: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'Precision scopes and optics study for heavy bolt-action sniper systems.',
    likes: 1200,
    likedByMe: false,
    views: 4800,
    tags: ['weapon', 'scope', 'tactical'],
    software: ['Maya'],
    createdAt: '2026-04-20',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-40',
    title: 'Hyperion Realms Cyber Core',
    artist: {
      name: 'Kenji Takahashi',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
      handle: 'kenjidigital',
      followedByMe: false,
      role: 'Environment Illustrator'
    },
    image: 'https://images.unsplash.com/photo-1534224039826-c7a0dea0e66a??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Concept artwork of multiple space-guards in dynamic golden high-tech armor uniforms.',
    likes: 1980,
    likedByMe: false,
    views: 8400,
    tags: ['hyperion', 'concept', 'cyber', 'guards'],
    software: ['Photoshop'],
    createdAt: '2026-04-19',
    comments: [],
    brandOverlay: undefined
  },

  {
    id: 'art-41',
    title: 'Glow retro Glass Lantern',
    artist: {
      name: 'Kaelen Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
      handle: 'kaelenv',
      followedByMe: false,
      role: 'Senior Matte Painter'
    },
    image: 'https://images.unsplash.com/photo-1517411032315-54ef2cb783bb??w=400&q=60&auto=format&fit=crop', 
    category: '2D',
    description: 'Immersive red-glowing brass lantern study. Focus on handpainted glass refraction.',
    likes: 1450,
    likedByMe: false,
    views: 6100,
    tags: ['lantern', 'glass', 'lighting'],
    software: ['Photoshop'],
    createdAt: '2026-04-18',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-42',
    title: 'Fighter Mechs sketch designs',
    artist: {
      name: 'Marcus Vance',
      avatar: 'https://images.unsplash.com/photo-1628157582853-a796fa650a6a?w=150&auto=format&fit=crop',
      handle: 'marcus_v',
      followedByMe: false,
      role: 'Digital Architect'
    },
    image: 'https://images.unsplash.com/photo-1544256718-3bcf237f3974??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'Dynamic rough linework and layout blocks for future mecha sentinel models.',
    likes: 1820,
    likedByMe: false,
    views: 7900,
    tags: ['mech', 'sketch', 'cyborg', 'character'],
    software: ['Procreate', 'Photoshop'],
    createdAt: '2026-04-17',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-43',
    title: 'Marathon Bolt: Astro Bakers Weapon',
    artist: {
      name: 'Aron Cole',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop',
      handle: 'aronc_art',
      followedByMe: false,
      role: 'Heavy Surface Modeler'
    },
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'Black and red customized assault firearm weapon labeled Marathon Fanart.',
    likes: 4200,
    likedByMe: false,
    views: 21000,
    tags: ['marathon', 'gun', 'hardsurface', 'fanart'],
    software: ['Maya', 'Substance Painter'],
    createdAt: '2026-04-16',
    comments: [],
    brandOverlay: 'MARATHON'
  },
  {
    id: 'art-44',
    title: 'Plate armored female Knight',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1519074069444-1ba4e6664104??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Strong full-body stance pose of a female knight lifting a heavy broadsword.',
    likes: 2900,
    likedByMe: false,
    views: 11000,
    tags: ['knight', 'armor', 'sword'],
    software: ['ZBrush', 'Blender'],
    createdAt: '2026-04-15',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-45',
    title: 'Pilot anime girl red scarf',
    artist: {
      name: 'Sera Arttech',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop',
      handle: 'sera_art',
      followedByMe: false,
      role: 'Digital Painter'
    },
    image: 'https://images.unsplash.com/photo-1560942485-b2a11cc13456??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'Portrait drawing of a cartoon aircraft pilot girl with red scarf and dynamic goggles.',
    likes: 3110,
    likedByMe: false,
    views: 14000,
    tags: ['anime', 'girl', 'illustrations', 'pilot'],
    software: ['Procreate', 'Photoshop'],
    createdAt: '2026-04-14',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-46',
    title: 'Short brown haired pilot warrior',
    artist: {
      name: 'Kenji Takahashi',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop',
      handle: 'kenjidigital',
      followedByMe: false,
      role: 'Environment Illustrator'
    },
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2??w=400&q=60&auto=format&fit=crop', 
    category: 'Illustration',
    description: 'High-contrast detailed anime fighter model with realistic shadows.',
    likes: 2150,
    likedByMe: false,
    views: 9400,
    tags: ['character', 'portrait', 'fighter'],
    software: ['Photoshop'],
    createdAt: '2026-04-13',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-47',
    title: 'Gothic Jester Clown Blue Hair',
    artist: {
      name: 'Lyra Sterling',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&auto=format&fit=crop',
      handle: 'lyraart',
      followedByMe: true,
      role: 'Lead Character Designer'
    },
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04??w=400&q=60&auto=format&fit=crop', 
    category: 'Characters',
    description: 'Close-up jester girl design with deep purple lips, gothic clown makeup and bright blue hair.',
    likes: 3990,
    likedByMe: false,
    views: 19500,
    tags: ['jester', 'gothic', 'clown', 'characters'],
    software: ['Photoshop', 'PaintTool SAI'],
    createdAt: '2026-04-12',
    comments: [],
    brandOverlay: undefined
  },
  {
    id: 'art-48',
    title: 'Bow carved horse figurehead decoration',
    artist: {
      name: 'Kaelen Vance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop',
      handle: 'kaelenv',
      followedByMe: false,
      role: 'Senior Matte Painter'
    },
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5??w=400&q=60&auto=format&fit=crop', 
    category: '3D',
    description: 'Study of ocean saltwater wood grain textures and custom carved horses on ancient tall ships.',
    likes: 4120,
    likedByMe: false,
    views: 18200,
    tags: ['sculpture', 'ocean', 'wood', 'figurehead'],
    software: ['ZBrush', 'Substance Painter'],
    createdAt: '2026-04-11',
    comments: [],
    brandOverlay: 'TIME-LIMITED'
  }
];
